// TermsAndConditions.js
import React from 'react';
import Breadcrumb from '../components/Breadcrumb';

const breadcrumbPaths = [{ label: 'Terms', url: '/terms' }];
function TermsAndConditions() {
  return (
    <div className='mt-[80px]'>
    <Breadcrumb paths={breadcrumbPaths} />
        <div className="container mx-auto p-4">
          <h1 className="text-4xl mb-4 font-montserrat font-normal pt-3 pb-7">Terms and Conditions</h1>

          <h2 className="text-xl font-montserrat font-semibold mb-2">1. TERMS OF USE</h2>
          <p className='font-poppins mb-8'>
              <h6 className='font-inter'>Service Availability and Termination:</h6> We may change, suspend, or terminate your use of the Services at our discretion. BuyBold may change, suspend or terminate your use of the Services with or without cause or notice to You, including, without limitation, if BuyBold believes that you have violated or acted inconsistently with the Agreement. In the event of termination, all your representations, warranties, indemnifications, and promises shall survive. Furthermore, sections 14-20 will continue to govern any claim or dispute. We may, but do not promise to store or keep any content that you have provided, liked or posted. BuyBold SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTY(S) FOR ANY LOSS OR DAMAGE THAT IS CAUSED BY OR ARISES FROM OR IN CONNECTION WITH ANY SUCH DISCONTINUATION OF SERVICES (INCLUDING, WITHOUT LIMITATION AND BY WAY OF EXAMPLE ONLY, REFUNDS, LOST PROFITS, LOST OPPORTUNITIES, MONETARY DAMAGES, DISRUPTION IN OR LOSS OF SERVICE, OR LOSS OF CONTENT).
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">2. User Generated Content</h2>
          <p className='font-poppins mb-8'>
              <h6 className='font-inter'>YOUR REPRESENTATIONS AND WARRANTIES:</h6> You own all of your Content. You represent, warrant and agree that you are the exclusive owner of your Content and/or you have all rights, licenses, consents and releases necessary for the Content that you make available on the Services, including the right to grant all of the rights and licenses in this Agreement without BuyBold incurring any third party obligations or liability arising out of its exercise of the rights thereto granted herein by you. You further represent, warrant and agree that your Content does not infringe, misappropriate or violate a third party's intellectual property rights, a third party's rights of publicity or privacy, or any other law or regulation.
          </p>

          {/* Add new sections below */}

          <h2 className="text-xl font-montserrat font-semibold mb-2">3. YOUR LICENSE TO buybold</h2>
          <p className='font-poppins mb-8'>
              You grant us a non-exclusive license to use your Content. You grant to buybold a non-exclusive, perpetual, worldwide, royalty-free license to use, host, store, transmit, reproduce, distribute, sublicense, modify, create derivative works, communicate, publish, publicly perform, publicly display, archive, and otherwise use and exploit such Content, in whole or in part, in any manner, medium, or form, whether now known or hereinafter devised, as buybold sees fit in its sole discretion, and includes without limitation use for the purpose of operating, promoting, and improving the Services. Without limiting the above, you grant to buybold the right to syndicate your Content for any purpose, including without limitation the right to use such syndicated Content to promote the buybold brand. You further grant to buybold all rights necessary to facilitate your use of a third party's site, app or services that require syndication or other use of your Content in connection with buybold.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">4. WARNINGS; DISCLAIMERS</h2>
          <p className='font-poppins mb-8'>
              If you choose to share content through the Services in areas that others can view, copy, and use, then you do so at your own risk. buybold IS NOT RESPONSIBLE FOR, AND EXPRESSLY DISCLAIMS ANY LIABILITY ARISING FROM OR IN CONNECTION WITH, THE USE OR DISCLOSURE OF ANY INFORMATION, COMMUNICATION, OR CONTENT THAT YOU VOLUNTARILY SUBMIT THROUGH THE SITES OR ANY OF THE APPS IN AREAS THAT OTHERS CAN VIEW, COPY AND USE.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">5. Inappropriate Content</h2>
          <p className='font-poppins mb-8'>
              You agree not to post or behave inappropriately. We reserve the right to determine if a post or act is offensive. You may not post inappropriate Content in connection with the Services. Inappropriate Content includes anything buybold, in its sole discretion, determines to be offensive or inappropriate for inclusion or use on the Services. It includes, without limitation, Content that:
              <ul className="list-disc pl-4">
                  <li>Impersonates any person or entity or falsely states or otherwise misrepresents your affiliation with any person or entity, or creates a false identity for purposes of misleading others;</li>
                  <li>Promotes or contains material that is illegal, harmful, threatening, abusive, harassing, false, misleading, tortious, defamatory, vulgar, obscene, libelous, sexually explicit, violent, invasive of another’s privacy, hateful, discriminatory based on race / sex / religion / nationality / disability / age / sexual orientation, directed toward children under 13 years of age pursuant to the Children’s Online Privacy Protection Act (see also, FTC’s Children’s Privacy Site at http://business.ftc.gov/privacy-and-security/childrens-privacy), or otherwise objectionable;</li>
                  <li>Infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party;</li>
                  <li>You do not have the right to disclose under contract or applicable law;</li>
                  <li>Contains software viruses or any other technology designed to interrupt, destroy or limit the functionality of the Services;</li>
                  <li>Involves the transmission of “junk mail”, “chain letters” or unsolicited mass e-mails — “spam”;</li>
                  <li>Uses automated scripts or other technology to collect information from or otherwise interact with the Services or other users without their consent;</li>
                  <li>Engages in advertising or other solicitation activities such as pyramid schemes, contests, or sweepstakes;</li>
                  <li>Provides material support or resources (or to conceal or disguise the nature, location, source, or ownership of material support or resources) to any organization(s) designated by the United States government as a foreign terrorist organization pursuant to section 219 of the Immigration and Nationality Act;</li>
                  <li>Includes other people's personally identifying information or other confidential information, such as credit card numbers, Social Security numbers, license numbers, passwords, phone numbers, addresses, and email addresses; or</li>
                  <li>Violates or encourages or facilitates the violation of any applicable local, state, national or international law, including but not limited to, regulations promulgated by the U.S. Securities and Exchange Commission, the New York Stock Exchange, the American Stock Exchange or the NASDAQ, and any regulations having the force of law.</li>
              </ul>
              Violating this Agreement may lead to you being immediately and permanently banned, with notification to your Internet Service Provider if deemed necessary.
          </p>

          {/* Add more sections as needed */}

          <h2 className="text-xl font-montserrat font-semibold mb-2">6. Links to Other Sites, Networks, Platforms, and Apps</h2>
          <p className='font-poppins mb-8'>
              The Services may contain links to third party sites, networks, platforms including advertisers. However, please be aware that buybold is not responsible for and cannot control the terms of service or privacy policies of such parties. We encourage you to be aware when you leave the Services, and to read the applicable agreements for each and every third party entity. The Agreement applies solely to these Services. buybold is not responsible for and makes no representations or warranties, including without limitation, the content, accuracy, opinions, functionality, or services provided in such third party websites.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">7. Use of Content in the Services</h2>
          <p className='font-poppins mb-8'>
              Our Services allow you to “shop your screenshots” and other content. However, it is possible that not all products and services will be available for purchase. The content contained in the Services, and the terms, conditions, and descriptions that appear, are subject to change. Not all products and services are available in all geographic areas. Your eligibility for particular products and services is subject to final determination by the Merchants.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">8. Access to Our Services</h2>
          <p className='font-poppins mb-8'>
              <h6 className='font-inter'>ELIGIBILITY</h6> To use our Services, you must (1) be at least 13 years of age and (2) be either old enough to lawfully enter into this Agreement yourself or have your parent or legal guardian do so. THE SERVICES ARE AVAILABLE ONLY TO INDIVIDUALS AGED 13 YEARS OF AGE OR OLDER. IF YOU ARE 13 OR OLDER, BUT UNDER THE APPLICABLE AGE OF MAJORITY IN YOUR STATE OR JURISDICTION OF RESIDENCE, THEN YOU AGREE TO REVIEW THIS AGREEMENT WITH A PARENT OR LEGAL GUARDIAN TO MAKE SURE YOU AND YOUR PARENT OR LEGAL GUARDIAN UNDERSTAND AND AGREE TO THIS AGREEMENT. IF YOU ARE THE PARENT OR LEGAL GUARDIAN AGREEING TO THE AGREEMENT FOR YOUR CHILD OVER 13 YEARS OF AGE, THEN YOU AGREE ON YOUR CHILD’S BEHALF AND FURTHER AGREE AND ACCEPT FULL RESPONSIBILITY FOR YOUR CHILD’S USE OF THE SERVICES. buybold DOES NOT ENCOURAGE, SOLICIT, OR PERMIT VISITORS TO THE SERVICES WHO ARE UNDER THE AGE OF 13.
              <h6 className='font-inter'>REGISTRATION</h6> You agree to provide certain information to set up your account. As part of the registration process, you will select a username and password and may provide certain information. You hereby consent to our access to and collection of such personal information about you. By registering for the Services, you hereby authorize buybold to send you emails and other communications. You agree to protect your password and not share your account with others. You are solely responsible for maintaining the confidentiality of your username and password. You may not authorize others to use your account, and you may not share, assign or otherwise transfer your account or login information to any other person or entity. You are responsible for any and all activities that are conducted through your account. buybold shall be entitled to assume that a user presenting your username and password is, in fact, you. You agree to notify buybold immediately of any unauthorized use of your account. buybold shall have the right at any time to change, modify or amend your username and password. You agree to provide correct information and keep it updated. You agree to only use our Services for personal reasons and not, for example, to compete with us. You represent and warrant that the information you provide to buybold is accurate, true, not confidential, and not in violation of any contractual obligations or other third party rights. You agree that it is your responsibility to keep your information accurate and updated. You represent and warrant that you are not a competitor of buybold and are not using the Services in competition with buybold. You further represent and warrant that you are using the Services solely for personal reasons and that you are not an attorney or an agent of an attorney conducting an investigation to a potential claim related to the Services, any materials available through the Services, or buybold.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">5. REGISTRATION</h2>
          <p className='font-poppins mb-8'>
              We may provide you updates from time to time and may require you to use the most updated version. buybold shall have the right in its sole discretion to substitute, replace, modify, update or upgrade (“updates”) the Services as buybold deems advisable; and, all such updates shall be incorporated in and subject to this Agreement and shall be the exclusive property of buybold. If buybold shall provide you with any updates, you will be required to utilize such version. buybold will only be required to support the most recent and current version provided to you. Depending on the update, You may not be able to use the Apps until You have downloaded the latest version and accepted any new terms that may apply. In case of a conflict between this Agreement and other terms provided with respect to updates, such other terms will prevail. This section will not require buybold to deliver new features and functionality nor any future products which may be offered.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">5. UPDATES</h2>
          <p className='font-poppins mb-8'>
              We may provide you updates from time to time and may require you to use the most updated version. buybold shall have the right in its sole discretion to substitute, replace, modify, update or upgrade (“updates”) the Services as buybold deems advisable; and, all such updates shall be incorporated in and subject to this Agreement and shall be the exclusive property of buybold. If buybold shall provide you with any updates, you will be required to utilize such version. buybold will only be required to support the most recent and current version provided to you. Depending on the update, You may not be able to use the Apps until You have downloaded the latest version and accepted any new terms that may apply. In case of a conflict between this Agreement and other terms provided with respect to updates, such other terms will prevail. This section will not require buybold to deliver new features and functionality nor any future products which may be offered.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">6. SUPPORT</h2>
          <p className='font-poppins mb-8'>
              We may provide user support. buybold reserves the right at any time to discontinue, cancel, or modify the technical support provided, if any.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">7. MESSAGES</h2>
          <p className='font-poppins mb-8'>
              You agree to receive messages from us, including marketing materials. You agree to receive messages, including notices and marketing materials, through the Services or through your contact information, such as email. It is your responsibility for ensuring that buybold has your current email address at all times. Any notice sent to you via such email address by buybold shall be deemed given, received, and read by you, whether or not it actually is received and/or read.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">8. AUTOMATED PROCESSING</h2>
          <p className='font-poppins mb-8'>
              Our Services allow you to “shop your screenshots” and other content. However, it is possible that not all products and services will be available for purchase. The content contained in the Services, and the terms, conditions, and descriptions that appear, are subject to change. Not all products and services are available in all geographic areas. Your eligibility for particular products and services is subject to final determination by the Merchants.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">9. Rights and Restrictions on Use</h2>
          <p className='font-poppins mb-8'>
              <h6 className='font-inter'>buybold'S LIMITED LICENSE TO YOU — APPS</h6> You agree to only use the Apps for personal reasons and understand that you may not copy or otherwise use the Apps in an unauthorized manner. Subject to your acceptance of this Agreement and your continuing compliance with this Agreement and any other relevant buybold policies, buybold grants to you a personal, non-exclusive, non-transferable, revocable limited license to download, access and use the Apps and related software (excluding source and object code) for your non-commercial, personal use on a mobile device or machine(s) of which you are the primary user. You may not copy, rent, lease, lend, sell, assign, transfer, distribute, sublicense or prepare derivative works of any of the Apps. If you sell or otherwise transfer to a third party a device on which an App is installed, you must remove the App from such device before doing so.
              <h6 className='font-inter'>buybold'S LIMITED LICENSE TO YOU — SITES</h6> You agree to only use the Sites for personal reasons and understand that you may not copy or otherwise use the Sites in an unauthorized manner. Subject to your acceptance of this Agreement and your continuing compliance with this Agreement and any other relevant buybold policies, buybold grants you a personal, non-exclusive, non-transferable, revocable limited license to access and use the Sites and to view the information and content found thereon. You may not copy, rent, lease, lend, sell, assign, transfer, distribute, sublicense or prepare derivative works of any of the Sites.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">10. WARNINGS; DISCLAIMERS</h2>
          <p className='font-poppins mb-8'>
              Our Services include content from third parties such as Influencers and Merchants, which we do not control. We disclaim any liability for such content. You understand that buybold does not accept any liability whatsoever for any harm that might result from any statements presented on the Services, including statements and opinions on the Services, products viewed via the Services, or third-party advertisements or services posted or linked through the Services. You understand that any statements by buybold, its employees, agents, and affiliates are provided for informational purposes only.buybold reserves the right to discontinue the Services or to change the content of the Services in any way and at any time, with or without notice to you, and without liability. buybold makes no predictions, warranties, or guarantees, express or implied, about the quality of any of the products or services advertised, offered, or provided by any Merchant, statements made by any Influencer, or other individual, company, or service provider utilizing the Services or featured on the Services and assumes no liability related thereto.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">11. RESTRICTIONS ON YOUR USE</h2>
          <p className='font-poppins mb-8'>
              You agree not to copy our Services, circumvent our security, or otherwise engage in prohibited conduct. You agree that systematic retrieval of data from the Services to create or compile directly or indirectly, in whole or in part, a collection, compilation, database or directory without the express written permission of buybold is strictly prohibited. You agree that you will not use any robot, spider, other automatic device, or manual process to monitor or copy our web pages or the content contained herein. You may not engage in the practices of “screen scraping,” “database scraping,” or any other practice or activity the purpose of which is to obtain lists of users, portions of a database, or other lists or information from the Services, in any manner or in any quantities not authorized by buybold. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of buybold or its affiliates without prior express written consent. You may not use any meta tags or any other “hidden text” utilizing buybold's name or trademarks without our express written consent. You agree that you will not use any device, software or routine to bypass any code which may be included to prevent you from breaching the obligations in this Section or to interfere or attempt to interfere with the proper working of the Services. You agree that you will not take any action that imposes an unreasonable or disproportionately large load on our or our host's infrastructure. You agree that you will not knowingly provide false information to sabotage or otherwise negatively affect the Services. You agree you will not reverse engineer, disassemble or decompile any buybold prototypes or software, nor any other systems, information, materials or objects which are provided to you or to which you are granted access hereunder. You agree to be bound by any application, forum, or specific rules published within the Services.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">12. Ownership of Intellectual Property</h2>
          <p className='font-poppins mb-8'>
              We own our intellectual property and only provide you a limited license to use our Services per this Agreement. You do not acquire any ownership rights by using our Services. Unless otherwise specified, all materials that are part of the Services are owned, controlled, or licensed by buybold and are protected by law from unauthorized use. The entire contents of the Services are protected under copyright, patent, trademark, and/or other intellectual property laws. buybold, the buybold logos, and all designs are trademarks and/or trade dress of buybold and may not be used without the express written permission of buybold. All other trademarks appearing on the Services are the property of their respective owners. You do not acquire any ownership rights by using the Services or downloading material from or uploading material to the Services. You agree not to (and shall not allow any third party to) reproduce, distribute, publish, prepare derivative works, publicly perform, publicly display, reverse engineer, reverse assemble or otherwise attempt to discover any source code, sell, assign, sublicense, or otherwise transfer or exploit any right in the Services, in whole or in part, except as expressly permitted herein. The limited licenses granted herein do not constitute a sale of the Apps or Sites, or any portion or copy thereof. RIGHTS NOT EXPRESSLY GRANTED HEREIN ARE RESERVED BY buybold. You agree to only use the Apps and Sites as expressly permitted herein.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">13. Digital Millennium Copyright Act</h2>
          <p className='font-poppins mb-8'>
              If you believe that your copyright has been infringed by a third party on our Services, then please follow this take down procedure. It is our policy to respond to notices of alleged infringement that comply with the Digital Millennium Copyright Act (the “DMCA”). If the information you are complaining about is located on a third party site or application, then you should contact that third party site or application. Please be aware that, in order to be effective, your notice of claim must comply with the detailed requirements set forth in the DMCA. You are encouraged to review them (see 17 U.S.C. § 512(c)(3)) before sending your claim. You may notify us of alleged infringement of intellectual property rights by contacting our Designated Agent at support@buybold.app Upon receipt of notice of claimed infringement, we will follow the procedures specified in the DMCA to resolve the claim between the notifying party and the alleged infringer who provided the content at issue. Please do not send any other communications to the Designated Agent, who is appointed solely for the purposes of receiving notices of copyright claims under the DMCA.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">14. Assignment</h2>
          <p className='font-poppins mb-8'>
              We may assign our rights and obligations, but you may not. buybold may assign its rights and obligations under this Agreement freely. You may not assign any rights or obligations under this Agreement without buybold's written consent.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">15. No Warranty/Disclaimers</h2>
          <p className='font-poppins mb-8'>
              We disclaim any warranties for our Service and provide them AS IS. YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. THE SERVICES ARE PROVIDED ON AN “AS IS”, “WHERE IS” AND “AS AVAILABLE” BASIS. TO THE FULL EXTENT ALLOWED BY LAW, buybold AND ITS OFFICERS, AGENTS, EMPLOYEES, AFFILIATES, SUBSIDIARIES, PARENTS, SUCCESSORS AND ASSIGNS (THE “buybold PARTIES”) EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, NON-INFRINGEMENT, TITLE, QUALITY, PERFORMANCE, NON-INTERFERENCE WITH INFORMATION, AND ACCURACY OF INFORMATIONAL CONTENT. THERE IS NO WARRANTY THAT INFORMATION PROVIDED HEREUNDER, OUR EFFORTS, OR THE SERVICES WILL FULFILL ANY OF YOUR PARTICULAR PURPOSES OR NEEDS. buybold PARTIES NEITHER ASSUME NOR AUTHORIZE ANY OTHER PERSON TO ASSUME FOR IT ANY OTHER LIABILITY IN CONNECTION WITH THE SALE AND USE OF THE SERVICES. buybold PARTIES ASSUME NO RESPONSIBILITY FOR ANY ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMMUNICATIONS LINE FAILURE, THEFT OR DESTRUCTION OR UNAUTHORIZED ACCESS TO, OR ALTERATION OF, THE SERVICES OR ANY USER COMMUNICATIONS. buybold PARTIES ARE NOT RESPONSIBLE FOR ANY INCORRECT OR INACCURATE CONTENT POSTED ON THE SERVICES, WHETHER CAUSED BY USERS OF THE SERVICES OR BY ANY OF THE EQUIPMENT OR PROGRAMMING ASSOCIATED WITH OR UTILIZED IN THE SERVICES. buybold PARTIES MAKE NO WARRANTY THAT YOUR USE OF THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; THE INFORMATION OR RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE; OR THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICES WILL MEET YOUR EXPECTATIONS. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES IS DONE AT YOUR OWN DISCRETION AND RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. NO INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE buybold PARTIES OR THROUGH THE SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE AGREEMENT. SOME JURISDICTIONS DO NOT ALLOW CERTAIN DISCLAIMERS, SO SOME OR ALL OF THIS SECTION MAY NOT APPLY TO YOU.
          </p>


          <h2 className="text-xl font-montserrat font-semibold mb-2">16. Limitation of Liability</h2>
          <p className='font-poppins mb-8'>
              This is the limit of our legal liability to you, if any. WHEN PERMITTED BY LAW, buybold PARTIES, TOGETHER WITH ANY THIRD PARTIES THAT MAY CONTRIBUTE TO OR BE AFFILIATED WITH THE SERVICES, SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF THEY HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES). THE FOREGOING PROVISION MAY HAVE THE EFFECT TO LIMITING THE LIABILITY OF THE buybold PARTIES FOR THEIR OWN NEGLIGENCE, INCLUDING THEIR OWN GROSS NEGLIGENCE. IF YOU ARE DISSATISFIED WITH THE SERVICES, OR ANY OF THE INFORMATION CONTAINED THEREON, OR REFUSE TO ABIDE BY THE AGREEMENT, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE YOUR USE. NOTWITHSTANDING THE FOREGOING, TO THE EXTENT PERMITTED BY LAW, buybold PARTIES’ TOTAL LIABILITY TO YOU SHALL NOT EXCEED THE AMOUNT YOU PAID TO USE THE SERVICES. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF CERTAIN LIABILITIES, SO SOME OR ALL OF THIS SECTION MAY NOT APPLY TO YOU.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">17. Indemnification</h2>
          <p className='font-poppins mb-8'>
              YOU AGREE TO DEFEND, INDEMNIFY AND HOLD COMPLETELY HARMLESS buybold PARTIES, TOGETHER WITH ANY THIRD PARTIES THAT MAY CONTRIBUTE TO OR BE AFFILIATED WITH THE SERVICES, FROM AND AGAINST ANY AND ALL CLAIMS, DAMAGES, COSTS, ATTORNEYS’ FEES, EXPENSES, AND SETTLEMENTS, WHETHER GROUNDED IN CONTRACT, TORT, STATUTE, LAW OR EQUITY, INCLUDING WITHOUT LIMITATION CLAIMS ARISING FROM OR RELATED TO YOUR USE OF THE SERVICES OR YOUR INABILITY TO USE THE SERVICES, THE MATERIALS THE SERVICES CONTAIN, ANY SITES OR APPLICATIONS LINKED TO THE SERVICES, ANY ALLEGED VIOLATION OF THE AGREEMENT, AND ANY ALLEGED VIOLATION OF THE RIGHTS OF A THIRD PARTY. THE FOREGOING PROVISION MAY HAVE THE EFFECT TO PROVIDING INDEMNITY TO THE buybold PARTIES LIABILITY AND DAMAGES ARISING FROM THEIR OWN NEGLIGENCE, INCLUDING THEIR OWN GROSS NEGLIGENCE. SOME JURISDICTIONS DO NOT ALLOW CERTAIN INDEMNIFICATIONS, SO SOME OR ALL OF THIS SECTION MAY NOT APPLY TO YOU.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">18. Choice of Law, Venue, Claim Resolution and Class Action Waiver</h2>
          <p className='font-poppins mb-8'>
              If there is ever a legal dispute between us, then we agree to resolve it in Delaware using State of Delaware law. The laws of the state of Texas, without application of conflict of law provisions, will apply to any disputes arising out of or relating to this Agreement or the Services. All claims arising out of or relating to this Agreement or the Services will be litigated exclusively in the federal or state courts of Dallas County, Texas. The Agreement is fully performable in Dallas County, Texas. The parties consent to personal jurisdiction in Dallas County, Texas and hereby waive any challenge to venue and personal jurisdiction they may have to a lawsuit filed in a state or federal court in Dallas County, Texas. If you are a consumer in the EEA, this won’t deprive you of any protection you have under the law of the country where you live and access to the courts in that country. You agree to raise any dispute within 2 years and waive your right to join a class action against buybold. Any dispute must be raised within two (2) years after the date the cause of action arose. Failure to provide the written documentation within this timeframe will render all claims related to the dispute null and void. You further agree not to join in any lawsuit with another person or serve as a class representative of any class action lawsuit against buybold.
          </p>

          <h2 className="text-xl font-montserrat font-semibold mb-2">19. Several Notes About This Agreement and Apple</h2>
          <p className='font-poppins mb-8'>
              If you downloaded the Apps from Apple’s App Store, then please review these additional terms. The following addresses certain matters with respect to Apple Inc. (“Apple”) and/or the so-called “Usage Rules” set forth in Apple's App Store Terms of Service (located at http://www.apple.com/legal/internet-services/itunes/us/terms.html) as of the effective date hereof (“Apple's Usage Rules”): Acknowledgement. The Parties hereby acknowledge that: this Agreement is between the Parties only, and not with Apple; Apple, and Apple's subsidiaries, are third-party beneficiaries of this Agreement; and Upon your acceptance of this Agreement, Apple will have the right (and will be deemed to have accepted the right) to enforce this Agreement against you as a third-party beneficiary hereof. Amended Scope of Limited License — The Apps. If you download, access, or use any of the Apps from or through Apple's App Store, then the limited license granted to you hereunder with respect to such Apps (see section 2(c) above) is hereby amended to add the following restriction: you may not use such Apps on any device other than the Apple-brand device (e.g., iPhone, iPod Touch, iPad) that you own or control, or in any manner that is contrary to Apple's Usage Rules.
          </p>
      </div></div>
  );
}

export default TermsAndConditions;
